<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [35]:
np.random.seed(42)
torch.manual_seed(42)



### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [15]:
arr = np.random.randint(0, 5, 6)
arr[0:]



array([3, 4, 2, 4, 4, 1])

In [3]:
# DON'T WRITE HERE

[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [16]:
# CODE HERE
x = torch.tensor(arr)
x


tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [4]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [20]:
x = x.type(torch.int64)
x


tensor([3, 4, 2, 4, 4, 1])

In [5]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [26]:
x = x.view(3, -1)
x


tensor([[3, 4],
        [2, 4],
        [4, 1]])

In [6]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [28]:
x[:,1:]



tensor([[4],
        [4],
        [1]])

In [7]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [30]:
torch.square(x)



tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [8]:
# DON'T WRITE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [36]:
y = torch.randint(0, 5, (2, 3))
y



tensor([[2, 2, 1],
        [4, 1, 0]])

In [9]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [37]:
x.mm(y)




tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

In [10]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!