In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

In [2]:
torch.manual_seed(101)

x = torch.randn(4, 4)
x

tensor([[-0.6028, -0.1208, -0.4323,  1.8811],
        [-0.7158,  0.0026,  0.2056,  0.5626],
        [ 0.2795, -1.0873,  0.0613,  0.9088],
        [-0.4134, -0.1937, -2.1826,  0.7185]])

In [3]:
mx = torch.max(x.data, dim=1)
mx

# torch.max(x, 0)   # Reduce across rows.
# torch.max(x, 1)   # Reduce across columns.

torch.return_types.max(
values=tensor([1.8811, 0.5626, 0.9088, 0.7185]),
indices=tensor([3, 3, 3, 3]))

In [4]:
a = torch.linspace(0, 50, 50).reshape(10, -1)
b = torch.linspace(50, 100, 50).reshape(10, -1)

print(a)
print(b)

tensor([[ 0.0000,  1.0204,  2.0408,  3.0612,  4.0816],
        [ 5.1020,  6.1224,  7.1429,  8.1633,  9.1837],
        [10.2041, 11.2245, 12.2449, 13.2653, 14.2857],
        [15.3061, 16.3265, 17.3469, 18.3673, 19.3878],
        [20.4082, 21.4286, 22.4490, 23.4694, 24.4898],
        [25.5102, 26.5306, 27.5510, 28.5714, 29.5918],
        [30.6122, 31.6327, 32.6531, 33.6735, 34.6939],
        [35.7143, 36.7347, 37.7551, 38.7755, 39.7959],
        [40.8163, 41.8367, 42.8571, 43.8776, 44.8980],
        [45.9184, 46.9388, 47.9592, 48.9796, 50.0000]])
tensor([[ 50.0000,  51.0204,  52.0408,  53.0612,  54.0816],
        [ 55.1020,  56.1224,  57.1429,  58.1633,  59.1837],
        [ 60.2041,  61.2245,  62.2449,  63.2653,  64.2857],
        [ 65.3061,  66.3265,  67.3469,  68.3673,  69.3878],
        [ 70.4082,  71.4286,  72.4490,  73.4694,  74.4898],
        [ 75.5102,  76.5306,  77.5510,  78.5714,  79.5918],
        [ 80.6122,  81.6327,  82.6531,  83.6735,  84.6939],
        [ 85.7143,  86.7347, 

In [5]:
c = torch.cat([a, b], dim=1)
print(c)

tensor([[  0.0000,   1.0204,   2.0408,   3.0612,   4.0816,  50.0000,  51.0204,
          52.0408,  53.0612,  54.0816],
        [  5.1020,   6.1224,   7.1429,   8.1633,   9.1837,  55.1020,  56.1224,
          57.1429,  58.1633,  59.1837],
        [ 10.2041,  11.2245,  12.2449,  13.2653,  14.2857,  60.2041,  61.2245,
          62.2449,  63.2653,  64.2857],
        [ 15.3061,  16.3265,  17.3469,  18.3673,  19.3878,  65.3061,  66.3265,
          67.3469,  68.3673,  69.3878],
        [ 20.4082,  21.4286,  22.4490,  23.4694,  24.4898,  70.4082,  71.4286,
          72.4490,  73.4694,  74.4898],
        [ 25.5102,  26.5306,  27.5510,  28.5714,  29.5918,  75.5102,  76.5306,
          77.5510,  78.5714,  79.5918],
        [ 30.6122,  31.6327,  32.6531,  33.6735,  34.6939,  80.6122,  81.6327,
          82.6531,  83.6735,  84.6939],
        [ 35.7143,  36.7347,  37.7551,  38.7755,  39.7959,  85.7143,  86.7347,
          87.7551,  88.7755,  89.7959],
        [ 40.8163,  41.8367,  42.8571,  43.8776,

In [6]:
d = F.log_softmax(a, dim=1)
print(a)
print(d)

tensor([[ 0.0000,  1.0204,  2.0408,  3.0612,  4.0816],
        [ 5.1020,  6.1224,  7.1429,  8.1633,  9.1837],
        [10.2041, 11.2245, 12.2449, 13.2653, 14.2857],
        [15.3061, 16.3265, 17.3469, 18.3673, 19.3878],
        [20.4082, 21.4286, 22.4490, 23.4694, 24.4898],
        [25.5102, 26.5306, 27.5510, 28.5714, 29.5918],
        [30.6122, 31.6327, 32.6531, 33.6735, 34.6939],
        [35.7143, 36.7347, 37.7551, 38.7755, 39.7959],
        [40.8163, 41.8367, 42.8571, 43.8776, 44.8980],
        [45.9184, 46.9388, 47.9592, 48.9796, 50.0000]])
tensor([[-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [-4.5225, -3.5021, -2.4817, -1.4613, -0.4409],
        [

In [16]:
x = torch.linspace(0, 10, 10).view(5, -1)
print(x)
print(x.stride())
print(x.is_contiguous())

tensor([[ 0.0000,  1.1111],
        [ 2.2222,  3.3333],
        [ 4.4444,  5.5556],
        [ 6.6667,  7.7778],
        [ 8.8889, 10.0000]])
(2, 1)
True


In [21]:
x = x.t()   # Transpose the tensor.
print(x)
print(x.stride())
print(x.is_contiguous())

print(x.view(-1))   # Cannot flatten the tensor because of non-contiguous.

tensor([[ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889],
        [ 1.1111,  3.3333,  5.5556,  7.7778, 10.0000]])
(1, 2)
False


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [24]:
# So make it contiguous.
x = x.contiguous()
print(x)
print(x.stride())
print(x.view(-1))

tensor([[ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889],
        [ 1.1111,  3.3333,  5.5556,  7.7778, 10.0000]])
(5, 1)
tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889,  1.1111,  3.3333,  5.5556,
         7.7778, 10.0000])
